#ifndef PINOUT_H
#define PINOUT_H

// PINS
extern int UART_ESP1_TX_PIN;
extern int UART_ESP1_RX_PIN;

extern int CUP_A_MOTOR_FORWARD_PIN;
extern int CUP_A_MOTOR_BACKWARD_PIN;
extern int CUP_A_SERVO_LEFT_PIN;
extern int CUP_A_SERVO_RIGHT_PIN;
extern int CUP_A_EXTEND_LIMIT_SWITCH_PIN;
extern int CUP_A_RETRACT_LIMIT_SWITCH_PIN;

extern int CUP_B_MOTOR_FORWARD_PIN;
extern int CUP_B_MOTOR_BACKWARD_PIN;
extern int CUP_B_SERVO_LEFT_PIN;
extern int CUP_B_SERVO_RIGHT_PIN;
extern int CUP_B_EXTEND_LIMIT_SWITCH_PIN;
extern int CUP_B_RETRACT_LIMIT_SWITCH_PIN;

extern int CUP_C_MOTOR_FORWARD_PIN;
extern int CUP_C_MOTOR_BACKWARD_PIN;
extern int CUP_C_SERVO_LEFT_PIN;
extern int CUP_C_SERVO_RIGHT_PIN;
extern int CUP_C_EXTEND_LIMIT_SWITCH_PIN;
extern int CUP_C_RETRACT_LIMIT_SWITCH_PIN;

extern int CUP_D_MOTOR_FORWARD_PIN;
extern int CUP_D_MOTOR_BACKWARD_PIN;
extern int CUP_D_SERVO_LEFT_PIN;
extern int CUP_D_SERVO_RIGHT_PIN;
extern int CUP_D_EXTEND_LIMIT_SWITCH_PIN;
extern int CUP_D_RETRACT_LIMIT_SWITCH_PIN;

#endif // PINOUT_H
